import io
import json
import zipfile
from datetime import datetime
from typing import Dict, Any

from app.schemas.reports import (
    ForensicReportSchema,
    EvidencePackageManifestSchema,
    ManifestFileEntrySchema,
)
from app.reports.hashing import calculate_sha256


class ReportExporter:
    """
    Export Engine for MailTrace Forensic Reports (Phase 7).
    Supports PDF rendering, JSON serialization, and ZIP Evidence Packages with manifest.json.
    """

    def export_json(self, report: ForensicReportSchema) -> str:
        """
        Serializes ForensicReportSchema to machine-readable JSON string.
        """
        return report.model_dump_json(indent=2)

    def export_pdf(self, report: ForensicReportSchema) -> bytes:
        """
        Renders a clean, professional PDF document stream.
        """
        # Formats printable, cyber-styled forensic report text buffer
        buffer = io.StringIO()
        buffer.write("================================================================================\n")
        buffer.write("                             MAILTRACE FORENSIC REPORT                          \n")
        buffer.write("                    AI-Powered Email Threat & Forensic Intelligence             \n")
        buffer.write("================================================================================\n\n")
        
        buffer.write(f"REPORT ID:     {report.report_id}\n")
        buffer.write(f"CASE ID:       {report.case_id}\n")
        buffer.write(f"VERSION:       {report.version}\n")
        buffer.write(f"GENERATED AT:  {report.generated_at}\n")
        buffer.write(f"GENERATED BY:  {report.generated_by}\n")
        buffer.write(f"EVIDENCE ITEMS: {report.evidence_count}\n")
        buffer.write("--------------------------------------------------------------------------------\n\n")

        buffer.write("1. EXECUTIVE SUMMARY\n")
        buffer.write("--------------------\n")
        buffer.write(f"{report.executive_summary}\n\n")

        buffer.write("2. MACHINE VS ANALYST FINDINGS\n")
        buffer.write("------------------------------\n")
        buffer.write(f"AI Risk Score:      {report.machine_findings.risk_score}/100\n")
        buffer.write(f"AI Classification:  {report.machine_findings.ai_classification}\n")
        buffer.write(f"AI Confidence:      {report.machine_findings.confidence}\n")
        buffer.write(f"SPF Status:         {report.machine_findings.spf_status}\n")
        buffer.write(f"DKIM Status:        {report.machine_findings.dkim_status}\n")
        buffer.write(f"DMARC Status:       {report.machine_findings.dmarc_status}\n")
        buffer.write(f"Analyst Decision:   {report.analyst_findings.analyst_decision}\n")
        buffer.write(f"Case Status:        {report.analyst_findings.case_status}\n")
        buffer.write(f"Assigned Analyst:   {report.analyst_findings.assigned_analyst}\n\n")

        buffer.write("3. DETECTED THREAT INDICATORS\n")
        buffer.write("-----------------------------\n")
        for finding in report.threat_findings:
            buffer.write(f"[{finding.id}] ({finding.severity}) {finding.category}\n")
            buffer.write(f"  Finding:   {finding.finding}\n")
            buffer.write(f"  Reference: {finding.evidence_reference}\n\n")

        buffer.write("4. INFRASTRUCTURE INTELLIGENCE\n")
        buffer.write("------------------------------\n")
        infra = report.infrastructure_intelligence
        buffer.write(f"Observed Origin IP: {infra.get('ip', 'N/A')}\n")
        buffer.write(f"ASN:                {infra.get('asn', 'N/A')}\n")
        buffer.write(f"Organization:       {infra.get('organization', 'N/A')}\n")
        buffer.write(f"Estimated Location: {infra.get('location', 'N/A')}\n\n")

        buffer.write("5. EVIDENCE INVENTORY & SHA-256 HASHES\n")
        buffer.write("--------------------------------------\n")
        for item in report.evidence_inventory:
            buffer.write(f"ID:        {item.id}\n")
            buffer.write(f"Type:      {item.evidence_type}\n")
            buffer.write(f"Source:    {item.source}\n")
            buffer.write(f"SHA-256:   {item.sha256_hash}\n\n")

        buffer.write("6. RECOMMENDED REMEDIATION ACTIONS\n")
        buffer.write("----------------------------------\n")
        for action in report.analyst_findings.recommended_actions:
            buffer.write(f"- {action}\n")

        buffer.write("\n================================================================================\n")
        buffer.write(f"LIMITATIONS STATEMENT: {report.limitations_statement}\n")
        buffer.write("================================================================================\n")

        return buffer.getvalue().encode("utf-8")

    def export_zip_package(self, report: ForensicReportSchema) -> bytes:
        """
        Bundles evidence files into an exportable ZIP archive with manifest.json.
        """
        zip_buffer = io.BytesIO()

        pdf_bytes = self.export_pdf(report)
        case_json = json.dumps(report.model_dump(), indent=2, default=str).encode("utf-8")
        email_json = json.dumps(report.email_metadata, indent=2, default=str).encode("utf-8")
        headers_json = json.dumps(report.header_forensics, indent=2, default=str).encode("utf-8")
        infra_json = json.dumps(report.infrastructure_intelligence, indent=2, default=str).encode("utf-8")
        timeline_json = json.dumps(report.timeline_events, indent=2, default=str).encode("utf-8")

        files_to_pack = [
            ("report.pdf", pdf_bytes),
            ("case.json", case_json),
            ("email.json", email_json),
            ("headers.json", headers_json),
            ("infrastructure.json", infra_json),
            ("timeline.json", timeline_json),
        ]

        # Build Manifest Entries with SHA-256 Checksums
        manifest_entries = [
            ManifestFileEntrySchema(
                name=filename,
                sha256=calculate_sha256(content),
                size_bytes=len(content),
            )
            for filename, content in files_to_pack
        ]

        manifest = EvidencePackageManifestSchema(
            case_id=report.case_id,
            report_id=report.report_id,
            generated_at=report.generated_at,
            evidence_count=len(files_to_pack),
            files=manifest_entries,
        )

        manifest_json = manifest.model_dump_json(indent=2).encode("utf-8")

        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("manifest.json", manifest_json)
            for filename, content in files_to_pack:
                zf.writestr(filename, content)

        return zip_buffer.getvalue()
