from enum import Enum

class ThreatCategory(str, Enum):
    LEGITIMATE = "LEGITIMATE"
    SUSPICIOUS = "SUSPICIOUS"
    PHISHING = "PHISHING"
    IMPERSONATION = "IMPERSONATION"
    BUSINESS_EMAIL_COMPROMISE = "BUSINESS_EMAIL_COMPROMISE"
    FINANCIAL_FRAUD = "FINANCIAL_FRAUD"
    CREDENTIAL_HARVESTING = "CREDENTIAL_HARVESTING"
    MALICIOUS_DELIVERY = "MALICIOUS_DELIVERY"
    UNKNOWN = "UNKNOWN"

class ThreatRiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
